name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.2

      - name: Install dependent
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test